### ISSUE TITLE
Migrate `adorsys-xmas-game`

### ISSUE THREAD

**Issue by nce** [adorsys/ops-adorsys-kubernetes-platform#59]
I will migrate this project and write documentation along the way.

**Comment by nce** [comment]
[fdefc93](https://github.com/adorsys/ops-k8s-bootstrap/commit/fdefc93c308aeaa9d71f72729a68dc76fcd7c23c)

**Comment by nce** [comment]
Still unsure about the currently existing CNAMES

**Comment by kimdre** [comment]
Migration ist bereits abgeschlossen.

**Comment by kimdre** [comment]
Projekt wird nicht mehr benötigt.
