### ISSUE TITLE
migration techradar

### ISSUE THREAD

**Issue by nce** [adorsys/ops-adorsys-kubernetes-platform#70]
*  [x] Adjust Gitlab Build
*  [x] Add CI Token in Gitlab
*  [x] Add applicaton in `showroom`
*  [x] Notified the project team
*  [x] referenced `default` branch
*  [x] openshift deletion

**Comment by nce** [comment]
added to monitoring [b50d2d6](https://github.com/adorsys/ops-adorsys-kubernetes-platform/commit/b50d2d697f1ff6fe5460bf1b18ad58d427f7c1ac)

**Comment by kimdre** [comment]
Migration completed.
