### ISSUE TITLE
Add new application: Sopra Mavenproxy

### ISSUE THREAD

**Issue by nce** [adorsys/ops-adorsys-kubernetes-platform#72]
Please provide us with answers for all the :wrench:-marked fields. The checkmarks will be **selected/marked by OPS**.

## Responsible
> Who/what project is resonsible for this service/app?

- [x] :wrench: `sopra`

## Cluster
> Where should we deploy your application? Has it public exposure (like marketing/promotion) and needs higher uptimes, or is it demo/test and can run in our playground

- [x] :wrench: `showroom`

## DNS/Domainname
> Which domain name is your ingress using

- [x] :wrench: maven-proxy.sopra.adorsys.io

## Monitoring
> Should we add your application in our monitoring?

- [x] :wrench: `yes`

**Comment by kimdre** [comment]
Migration completed and successfully tested.

**Comment by kimdre** [comment]
The migration branch needs to be merged to master, for me to able to change targetRevision also to master how it should be.

**Comment by kimdre** [comment]
Migration completed.
